services:
  n8n:
    image: n8nio/n8n:1.40.0
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_LOG_LEVEL=debug
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=mysecretpassword
    volumes:
      - ./.n8n:/home/node/.n8n
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
